const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const admin=require('firebase-admin'),crypto=require('node:crypto');
admin.initializeApp();const db=admin.firestore();
const workerURL=defineSecret('WORKER_URL'),workerSecret=defineSecret('WORKER_SHARED_SECRET'),encryptionKey=defineSecret('TOKEN_ENCRYPTION_KEY');
function user(req){if(!req.auth?.uid)throw new HttpsError('unauthenticated','Sign in required');return req.auth.uid;}
function key(){const k=Buffer.from(encryptionKey.value(),'base64');if(k.length!==32)throw Error('Encryption key must be 32 bytes');return k;}
function encrypt(s){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const v=Buffer.concat([c.update(s,'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),v.toString('base64')].join('.');}
function decrypt(s){const[i,t,v]=s.split('.'),d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64'));d.setAuthTag(Buffer.from(t,'base64'));return Buffer.concat([d.update(Buffer.from(v,'base64')),d.final()]).toString('utf8');}
async function gh(token,path,method='GET',body){const r=await fetch('https://api.github.com'+path,{method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','User-Agent':'codex-control','X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new HttpsError('failed-precondition','GitHub: '+(d.message||r.status));return d;}
async function token(uid){const s=await db.doc('connections/'+uid).get();if(!s.exists)throw new HttpsError('failed-precondition','Connect GitHub first');return decrypt(s.data().token);}
const standard={region:'us-central1',secrets:[encryptionKey]};
exports.connectGitHub=onCall(standard,async(req)=>{const uid=user(req),t=String(req.data?.token||'').trim();if(!/^\S{20,500}$/.test(t))throw new HttpsError('invalid-argument','Invalid token');const me=await gh(t,'/user');await db.doc('connections/'+uid).set({token:encrypt(t),login:me.login,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{login:me.login};});
exports.disconnectGitHub=onCall(standard,async(req)=>{await db.doc('connections/'+user(req)).delete();return{ok:true};});
exports.listRepos=onCall(standard,async(req)=>{const t=await token(user(req));const [me,repos]=await Promise.all([gh(t,'/user'),gh(t,'/user/repos?per_page=100&sort=updated&affiliation=owner,collaborator,organization_member')]);return{login:me.login,repos:repos.filter(r=>r.permissions?.push).map(r=>({full_name:r.full_name,default_branch:r.default_branch,private:r.private}))};});
const taskCfg={region:'us-central1',secrets:[encryptionKey,workerURL,workerSecret],timeoutSeconds:60};
async function dispatch(payload){const r=await fetch(workerURL.value(),{method:'POST',headers:{'content-type':'application/json','x-worker-secret':workerSecret.value()},body:JSON.stringify(payload),signal:AbortSignal.timeout(25000)});const d=await r.json().catch(()=>({error:'Invalid worker response'}));if(!r.ok)throw Error(d.error||'Worker failed');return d;}
exports.createTask=onCall(taskCfg,async(req)=>{const uid=user(req),v=req.data||{},repo=String(v.repo||''),prompt=String(v.prompt||'').trim(),model=String(v.model||''),base=String(v.baseBranch||''),branch=String(v.outputBranch||'');if(!/^[\w.-]+\/[\w.-]+$/.test(repo)||!prompt||prompt.length>12000||!/^[\w.-]{1,100}$/.test(base)||!['','gpt-5.3-codex','gpt-5.2-codex'].includes(model))throw new HttpsError('invalid-argument','Invalid task');if(branch&&!/^codex\/[a-zA-Z0-9._/-]{1,100}$/.test(branch))throw new HttpsError('invalid-argument','Branch must start with codex/');const t=await token(uid),info=await gh(t,'/repos/'+repo);if(!info.permissions?.push)throw new HttpsError('permission-denied','Repository not writable');const ref=db.collection('users').doc(uid).collection('tasks').doc(),outputBranch=branch||'codex/task-'+ref.id.slice(0,12);await ref.set({repo,prompt,model,baseBranch:base,outputBranch,status:'dispatching',createdAt:admin.firestore.FieldValue.serverTimestamp()});await ref.collection('events').add({type:'system',message:'Request accepted',createdAt:admin.firestore.FieldValue.serverTimestamp()});try{await dispatch({action:'start',uid,taskId:ref.id,repo,prompt,model,baseBranch:base,outputBranch,githubToken:t});await ref.update({status:'queued'});}catch(e){await ref.update({status:'error',error:e.message});throw new HttpsError('unavailable',e.message);}return{taskId:ref.id};});
exports.syncTask=onCall(taskCfg,async(req)=>{const uid=user(req),id=String(req.data?.taskId||'');if(!/^[\w-]{10,40}$/.test(id))throw new HttpsError('invalid-argument','Invalid task ID');const snap=await db.doc('users/'+uid+'/tasks/'+id).get();if(!snap.exists)throw new HttpsError('not-found','Task missing');return dispatch({action:'sync',uid,taskId:id,repo:snap.data().repo,githubToken:await token(uid)});});
